export const profileActions = {
    FETCH_USER_REQUEST: "FETCH_USER_REQUEST",
    FETCH_USER_SUCCESS: "FETCH_USER_SUCCESS",
    FETCH_USER_FAILURE: "FETCH_USER_FAILURE",

    FETCH_USER_PHOTOS_REQUEST: "FETCH_USER_PHOTOS_REQUEST",
    FETCH_USER_PHOTOS_SUCCESS: "FETCH_USER_PHOTOS_SUCCESS",
    FETCH_USER_PHOTOS_FAILURE: "FETCH_USER_PHOTOS_FAILURE",
}

