export const searchActions = {
    FETCH_SEARCHED_PHOTOS_REQUEST: "FETCH_SEARCHED_PHOTOS_REQUEST",
    FETCH_SEARCHED_PHOTOS_SUCCESS: "FETCH_SEARCHED_PHOTOS_SUCCESS",
    FETCH_SEARCHED_PHOTOS_FAILURE: "FETCH_SEARCHED_PHOTOS_FAILURE",

    FETCH_MORE_SEARCHED_PHOTOS_REQUEST: "FETCH_MORE_SEARCHED_PHOTOS_REQUEST",
    FETCH_MORE_SEARCHED_PHOTOS_SUCCESS: "FETCH_MORE_SEARCHED_PHOTOS_SUCCESS",
    FETCH_MORE_SEARCHED_PHOTOS_FAILURE: "FETCH_MORE_SEARCHED_PHOTOS_FAILURE",
}