export const FETCH_CHOSEN_PHOTO_REQUEST = "FETCH_CHOSEN_PHOTO_REQUEST";
export const FETCH_CHOSEN_PHOTO_SUCCESS = "FETCH_CHOSEN_PHOTO_SUCCESS";
export const FETCH_CHOSEN_PHOTO_FAILURE = "FETCH_CHOSEN_PHOTO_FAILURE";

export const viewPhotoActions = {
    FETCH_CHOSEN_PHOTO_REQUEST: "FETCH_CHOSEN_PHOTO_REQUEST",
    FETCH_CHOSEN_PHOTO_SUCCESS: "FETCH_CHOSEN_PHOTO_SUCCESS",
    FETCH_CHOSEN_PHOTO_FAILURE: "FETCH_CHOSEN_PHOTO_FAILURE",

    CLOSE_MODAL: "CLOSE_MODAL"
}

